name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install libusb-dev
      - run: make dwdebug
      - run: ./dwdebug help,q

# vim: ts=2 sw=2 expandtab
